import type { Metadata } from "next";

import "../style/globals.css";
import { ThemeProvider } from "@components/theme-provider";
import { ThemeSelect } from "@components/ThemeSelect";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThemeSelect />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
